/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservaRouteImport } from './routes/reserva'
import { Route as SpelhoRouteImport } from './routes/spelho'
import { Route as ColecoesSlugRouteImport } from './routes/colecoes/$slug'
import { Route as ProdutoProductIdRouteImport } from './routes/produto/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaRoute = ReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const SpelhoRoute = SpelhoRouteImport.update({
  id: '/spelho',
  path: '/spelho',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesSlugRoute = ColecoesSlugRouteImport.update({
  id: '/colecoes/$slug',
  path: '/colecoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoProductIdRoute = ProdutoProductIdRouteImport.update({
  id: '/produto/$productId',
  path: '/produto/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reserva': typeof ReservaRoute
  '/spelho': typeof SpelhoRoute
  '/colecoes/$slug': typeof ColecoesSlugRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reserva': typeof ReservaRoute
  '/spelho': typeof SpelhoRoute
  '/colecoes/$slug': typeof ColecoesSlugRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reserva': typeof ReservaRoute
  '/spelho': typeof SpelhoRoute
  '/colecoes/$slug': typeof ColecoesSlugRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/reserva' | '/spelho' | '/colecoes/$slug' | '/produto/$productId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reserva' | '/spelho' | '/colecoes/$slug' | '/produto/$productId'
  id:
    | '__root__'
    | '/'
    | '/reserva'
    | '/spelho'
    | '/colecoes/$slug'
    | '/produto/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReservaRoute: typeof ReservaRoute
  SpelhoRoute: typeof SpelhoRoute
  ColecoesSlugRoute: typeof ColecoesSlugRoute
  ProdutoProductIdRoute: typeof ProdutoProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva': {
      id: '/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof ReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spelho': {
      id: '/spelho'
      path: '/spelho'
      fullPath: '/spelho'
      preLoaderRoute: typeof SpelhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes/$slug': {
      id: '/colecoes/$slug'
      path: '/colecoes/$slug'
      fullPath: '/colecoes/$slug'
      preLoaderRoute: typeof ColecoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$productId': {
      id: '/produto/$productId'
      path: '/produto/$productId'
      fullPath: '/produto/$productId'
      preLoaderRoute: typeof ProdutoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReservaRoute: ReservaRoute,
  SpelhoRoute: SpelhoRoute,
  ColecoesSlugRoute: ColecoesSlugRoute,
  ProdutoProductIdRoute: ProdutoProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
